name: Build and Deploy Storybook to Netlify
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  build-deploy-netlify:
    timeout-minutes: 18
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Env Vars
        run: source ./.github/scripts/setup-env-vars.sh
        env:
          GITHUB_EVENT_NUMBER: ${{ github.event.number }}
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ubuntu-latest-node-16.x-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ubuntu-latest-node-16.x-yarn-
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: |
          # Remove .npmrc if exits
          rm -rf .npmrc
          yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        run: yarn build-storybook
      - name: Deploy to Netlify
        id: deploy
        uses: nwtgck/actions-netlify@v1
        with:
          publish-dir: './storybook-static'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Branch: ${{ steps.branch-name.outputs.current_branch }} - Event: ${{ github.event.number }}'
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: false
          alias: ${{ env.STORYBOOK_NETLIFY_ALIAS }}
          github-deployment-environment: ${{ env.STORYBOOK_NETLIFY_ENVIRONMENT }}
          production-deploy: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STORYBOOK }}
        timeout-minutes: 1
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 'storybook-static'
          path: storybook-static
